### ISSUE TITLE
Just created a new Trezor wallet with wiped wallet. Next does not work

### ISSUE THREAD

**Issue by ghost** [Multibit-Legacy/multibit-hd#317]
I just created a new Trezor wallet with a wiped device.
Wallet created ok but on the Requesting Unlock screen the next button is doing nothing.
No errors in the log

After restart of MBHD, plug out/ plugin of Trezor it synced ok

**Comment by gary-rowe** [comment]
I've created a bunch of Trezor wallets and experienced no problems. I think this issue has been resolved as a result of the work carried out in #318.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
This still isn't quite right.
If I create a wallet now from a blank Trezor it creates ok but now, after the 12th word has confirmed and MBHD is showing the timestamp screen the Trezor traverses to the PIN matrix screen.

When the user clicks next on MBHD it then gets confused and sits on 'Communicating with trezor.

**Comment by bitcoin-solutions** [comment]
If you are really quick on the timestamp screen and press next before the PIN matrix appears then it works!
